name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (dev, staging, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    env:
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.0'
          
      - name: Terraform Init
        run: |
          cd infrastructure/terraform
          terraform init
      
      - name: Terraform Workspace
        run: |
          cd infrastructure/terraform
          ENVIRONMENT="${{ github.event.inputs.environment }}"
          terraform workspace select $ENVIRONMENT || terraform workspace new $ENVIRONMENT
      
      - name: Terraform Plan
        run: |
          cd infrastructure/terraform
          terraform plan -out=tfplan
      
      - name: Terraform Apply
        run: |
          cd infrastructure/terraform
          terraform apply tfplan
      
      - name: Summarize Outputs
        run: |
          cd infrastructure/terraform
          echo "## Terraform Outputs" >> $GITHUB_STEP_SUMMARY
          
          echo "* **S3 Bucket**: $(terraform output -raw s3_bucket_name)" >> $GITHUB_STEP_SUMMARY
          echo "* **API Gateway URL**: $(terraform output -raw api_gateway_url)" >> $GITHUB_STEP_SUMMARY
          echo "* **EC2 IP Address**: $(terraform output -raw ec2_instance_public_ip)" >> $GITHUB_STEP_SUMMARY
          echo "* **Dashboard URL**: http://$(terraform output -raw ec2_instance_public_ip)" >> $GITHUB_STEP_SUMMARY
