name: Terraform Deploy

on:
  push:
    branches: [ main, master ]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-deploy.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (dev, staging, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  terraform:
    name: 'Terraform Deploy'
    runs-on: ubuntu-latest
    
    env:
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.0'
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}
          
      - name: Terraform Init
        run: |
          cd terraform
          terraform init
      
      - name: Terraform Workspace
        run: |
          cd terraform
          ENVIRONMENT="${{ github.event.inputs.environment || 'dev' }}"
          terraform workspace select $ENVIRONMENT || terraform workspace new $ENVIRONMENT
      
      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -out=tfplan
      
      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply tfplan
